--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    gpu: "false"
    kind: model
  name: categorizer
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: categorizer
  template: 
    metadata: 
      labels: 
        app: categorizer
    spec: 
      containers: 
        - 
          args: 
            - "-c"
            - |
                gsutil -m cp -r gs://vi-inference-models-dev/categorizer/2020_efficientnet_b0/0000010 /model && \
                tensorflow_model_server --rest_api_port=8080 --model_name=categorizer \
                --model_base_path=/model
          command: 
            - /bin/sh
          
          image: eu.gcr.io/vi2-dev/tfserving
          lifecycle: 
            preStop: 
              exec: 
                command: 
                  - sleep
                  - "15"
          name: user-container
          ports: 
            - 
              containerPort: 8080
              name: tfserving-port
          readinessProbe: 
            httpGet: 
              path: /v1/models/categorizer
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
          resources: 
            limits: 
              cpu: 2
              memory: 4Gi
            requests: 
              cpu: 500m
              memory: 2Gi
      nodeSelector: 
        cloud.google.com/gke-nodepool: inf-cpu-pool
